# Config
home: false  # True : Set home as latest post, False : Set home as an index

# Header

background: eagle.jpeg

# Library
fancybox: false

# Widget
# Widget List : category, tag, archive, recent_posts
widgets:
- tag
- category
- recent_posts

# Google Analytics
ga_id : UA-68195561-2